/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Ventana;

/**
 *
 * @author PC
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonConoceMas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonIniciarSesionPaciente = new javax.swing.JButton();
        jButtonIniciarSesionDoctor = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonIniciarSesionDoctor1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        setPreferredSize(new java.awt.Dimension(900, 580));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(60, 91, 111));
        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 330, 60));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel1.setText("Clínica Capitan Peru");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, 40));

        jButtonConoceMas.setBackground(new java.awt.Color(60, 91, 111));
        jButtonConoceMas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonConoceMas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConoceMas.setText("Conoce sobre nosotros");
        jButtonConoceMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConoceMasActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonConoceMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 330, 60));

        jPanel1.setBackground(new java.awt.Color(21, 52, 72));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 270, 580));

        jButtonIniciarSesionPaciente.setBackground(new java.awt.Color(60, 91, 111));
        jButtonIniciarSesionPaciente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonIniciarSesionPaciente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIniciarSesionPaciente.setText("Iniciar sesión como paciente");
        jButtonIniciarSesionPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesionPacienteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonIniciarSesionPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 330, 60));

        jButtonIniciarSesionDoctor.setBackground(new java.awt.Color(60, 91, 111));
        jButtonIniciarSesionDoctor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonIniciarSesionDoctor.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIniciarSesionDoctor.setText("Iniciar sesión como doctor");
        jButtonIniciarSesionDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesionDoctorActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonIniciarSesionDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 330, 60));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        jButtonIniciarSesionDoctor1.setBackground(new java.awt.Color(60, 91, 111));
        jButtonIniciarSesionDoctor1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonIniciarSesionDoctor1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIniciarSesionDoctor1.setText("Iniciar sesión como recepcionista");
        jButtonIniciarSesionDoctor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesionDoctor1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonIniciarSesionDoctor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 330, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConoceMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConoceMasActionPerformed
        // TODO add your handling code here:
        VentanaMenuConoceInfo objVentanaConoceInfo = new VentanaMenuConoceInfo();
        objVentanaConoceInfo.setSize(900, 580);
        objVentanaConoceInfo.setLocationRelativeTo(null);
        objVentanaConoceInfo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonConoceMasActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonIniciarSesionPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionPacienteActionPerformed
        // TODO add your handling code here:
        VentanaLoginPaciente objVentanaLoginPaciente = new VentanaLoginPaciente();
        objVentanaLoginPaciente.setLocationRelativeTo(null);
        objVentanaLoginPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonIniciarSesionPacienteActionPerformed

    private void jButtonIniciarSesionDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionDoctorActionPerformed
        // TODO add your handling code here:
        VentanaLoginDoctor objVentanaLoginDoctor = new VentanaLoginDoctor();
        objVentanaLoginDoctor.setLocationRelativeTo(null);
        objVentanaLoginDoctor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonIniciarSesionDoctorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonIniciarSesionDoctor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionDoctor1ActionPerformed
        // TODO add your handling code here:
        VentanaLoginRecepcionista objVentanaLoginRecepcionista = new VentanaLoginRecepcionista();
        objVentanaLoginRecepcionista.setLocationRelativeTo(null);
        objVentanaLoginRecepcionista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonIniciarSesionDoctor1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonConoceMas;
    private javax.swing.JButton jButtonIniciarSesionDoctor;
    private javax.swing.JButton jButtonIniciarSesionDoctor1;
    private javax.swing.JButton jButtonIniciarSesionPaciente;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
